### ISSUE TITLE
Bootswatch materia not working

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#51]
@abhaychawla looks like bootswatch materia is no longer working. Same reason I commented out font-awesome because it was not working.
Please take a look

**Comment by abhaychawla** [comment]
Yes, something seems wrong. I'll have a look.

**Comment by anweshknayak** [comment]
fixed with https://github.com/openMF/web-app/commit/ca6ba8179e1450357275741f2363712507e0db65

**Comment by abhaychawla** [comment]
@anweshknayak Its still showing incorrectly. You should have told me you were looking into it before sending the PR. Let me have a look as you asked me to.

**Comment by anweshknayak** [comment]
@abhaychawla fixed it. do a hard refresh

**Comment by abhaychawla** [comment]
Yes, sorry it was an issue from my side.

**Comment by anweshknayak** [comment]
@abhaychawla sure I will tell you. I was just looking into it. And saw there error fixed it.
